#!/usr/bin/env bash
function usage() {
    echo ""
    echo "Used to generate protoc files for a known language, and to generate grpc"
    echo "files easily"
    echo ""
    echo "  required arguments:"
    echo "    --language    the language to generate in grpc, can be a csv"
    echo ""
    echo "  optional arguments:"
    echo "    --grpc        If grpc files should be included for the language"
}

langs=""
grpc=""

while [ $# ];do case $1 in
    --language) langs="${2}"; shift ;;
    --grpc) grpc="true";;
    --help) usage; exit 0 ;;
    *) break ;;
esac; shift; done

echo ${langs}
if [[ -z ${langs} ]]; then
    echo "Missing required parameter: --language"
    usage
    exit 1
fi

set -eu
cmd="protoc "
for lang in $(echo "${langs}" | tr ',' ' '); do
    echo "processing lang=${lang}"
    cmd="${cmd} --${lang}_out=."
    if [[ ${grpc} ]]; then
        echo "adding grpc flag for ${lang}"
        cmd="${cmd} --grpc_out=. --plugin=protoc-gen-grpc=/usr/bin/grpc_${lang}_plugin "
    fi
    echo "using cmd=${cmd}"
    proto=""
    for proto in $(find . -name \*.proto -print); do
        echo "running for ${proto} file"
        eval "${cmd} --proto_path=. ${proto}"
        echo "finished ${proto} file"
    done
    if [[ -z "${proto}" ]]; then
        echo "no .proto files found in working directory!"
        exit 1
    fi
    echo "finished processing for ${lang}"
done
echo "all finished"


